name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: show generators
      run: cmake --help
      working-directory: heif/build
    - name: configure
      run: cmake ../srcs -G"<Generator listed by above command for your target platform>"
      working-directory: heif/build
    - name: build
      run: cmake --build .
      working-directory: heif/build

