name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build C++ Library
      uses: lukka/run-cmake@v2
      with:
        buildDirectory: '${{ github.workspace }}/build/'
        cmakeListsTxtPath: '${{ github.workspace }}/srcs/CMakeLists.txt'
    - name: Build Java Library
      uses: eskatos/gradle-command-action@v1.3.2
      with:
        arguments: build
        gradle-version: 6.5
        build-root-directory: build/java-desktop
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: "Java Library"
        # Directory containing files to upload
        path: build/java-desktop/build/
